---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-gofarm
  labels:
    name: gofarm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofarm
  namespace: demo-gofarm
  labels:
    app: gofarm
spec:
  selector:
    matchLabels:
      app: gofarm
  replicas: 2
  template:
    metadata:
      labels:
        app: gofarm
    spec:
      containers:
      - name: gofarm
        image: registry.cn-hangzhou.aliyuncs.com/forufamily-bigdata/mygofarm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: gofarm-service
  namespace: demo-gofarm
  labels:
    app: gofarm
spec:
  type: NodePort
  selector:
    app: gofarm
  ports:
    - protocol: TCP
      port: 9081
      targetPort: 8081
      nodePort: 30981
      name: gofarm-tcp