name: "web_app"
mode: "dev"
port: 8081
version: "1.0.1"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "test"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: "%1q2w3e4r%"
  db: 0
  poolsize: 100
mongo:
  host: "10.0.0.120"
  port: 30075
kafka:
  hostport: "10.0.0.121:30092"
es:
  addresses:
    - "http://localhost:9200"
    - "http://localhost:9200"

