definitions:
  Response._ResponsePostList:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/Response.ResCode'
        description: 业务响应状态码
      data:
        description: 数据
        type: string
      message:
        description: 提示信息
        type: string
    type: object
  Response.ResCode:
    enum:
    - 1000
    - 1001
    - 1002
    - 1003
    - 1004
    - 1005
    - 1006
    - 1007
    - 1008
    type: integer
    x-enum-varnames:
    - CodeSuccess
    - CodeInvalidParams
    - CodeUserExist
    - CodeUserNotExist
    - CodeInvalidPassword
    - CodeServerBusy
    - CodeInvalidToken
    - CodeInvalidAuthFormat
    - CodeNotLogin
  User.SignDelModelHandler:
    properties:
      id:
        description: Id 用户主键ID
        type: integer
    type: object
  mygofarm_Models_User.GetoneUserModelHandler:
    properties:
      id:
        description: Id 用户主键ID
        type: integer
    type: object
  mygofarm_Models_User.LoginModelHandler:
    properties:
      password:
        description: Password description
        type: string
      username:
        description: Username description
        type: string
    type: object
  mygofarm_Models_User.SignModelHandler:
    properties:
      email:
        description: Email 用户email
        type: string
      gender:
        description: Gender 用户性别
        type: string
      password:
        description: Password 用户密码
        type: string
      repassword:
        description: RePassword 二次密码验证
        type: string
      userid:
        description: UserId 用户ID
        type: integer
      username:
        description: Username 用户名称
        type: string
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: 用户根据用户名、密码登录
      parameters:
      - description: req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/mygofarm_Models_User.LoginModelHandler'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response._ResponsePostList'
      summary: 用户登录接口
      tags:
      - 用户登录相关接口
  /api/signadd:
    post:
      consumes:
      - application/json
      description: 用户ID、名称、密码、性别、Emaill
      parameters:
      - description: req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/mygofarm_Models_User.SignModelHandler'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response._ResponsePostList'
      summary: 用户注册接口
      tags:
      - 用户注册接口
  /api/signdel:
    post:
      consumes:
      - application/json
      description: 用户主键ID
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/User.SignDelModelHandler'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 用户删除接口
      tags:
      - 用户删除接口
  /api/signone:
    post:
      consumes:
      - application/json
      description: 用户主键ID
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/mygofarm_Models_User.GetoneUserModelHandler'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 获取单个用户信息接口
      tags:
      - 获取单个用户信息接口
swagger: "2.0"
